spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jna?serverTimezone=JST
    username: Junko
    password: Junko

mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true